version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm run install:ui
  build:
    commands:
      - npm run build:ui
artifacts:
  files:
    - ui/build/**/*
